### ISSUE TITLE
Terminal node is a security risk

### ISSUE THREAD

**Issue by fofr** [nullquant/ComfyUI-BrushNet#141]
Allowing a workflow to run any code in the terminal is dangerous.

https://github.com/nullquant/ComfyUI-BrushNet/blob/f27e88c77e764f6ee6ade2bfa2e53a9f2c6edbd5/__init__.py#L13-L36

**Comment by nullquant** [comment]
This node is for debug, and yes it can be dangerous. But as any other custom node, no? What algorithm of security breach do you have in mind?

**Comment by fofr** [comment]
I’ve observed someone using this node to wget a script and remote execute it.

**Comment by BennyKok** [comment]
Oh hey @fofr we had the exact same situation with a user doing that and installing lolminer on ComfyDeploy. Would down to chat more about this.

**Comment by nullquant** [comment]
Ok, removed it.

**Comment by rafa-br34** [comment]
> This node is for debug, and yes it can be dangerous. But as any other custom node, no? What algorithm of security breach do you have in mind?

One can simply find hosts running ComfyUI (a simple Censys query like [such](https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=100&virtual_hosts=EXCLUDE&q=services.http.response.html_title%3DComfyUI) returns 700~ hosts) and run a reverse shell on it.
My solution to this problem is to use [ComfyUI-Login](https://github.com/liusida/ComfyUI-Login).
